// Per-category seed banks: Nairobi-flavored name parts, blurbs, tags, lanes.
// Combos (prefix x core x suffix) always yield 6+ unique names per subcategory.
// `secondary` lists multi-service tags (owner-approved: e.g. cars + safaris).

export interface CategoryBank {
  center: "kilimani" | "westlands" | "cbd" | "karen" | "eastleigh" | "jkia";
  kind: string;
  vertical: string;
  secondary: string[];
  cores: string[];
  premiumCores: string[];
  prefixes: string[];
  suffixes: string[];
  blurbs: string[];
  tags: string[];
  etaMin: [string, string];
  minOrderKes: [number, number];
}

const P = (arr: string[]) => arr;

export const BANKS: Record<string, CategoryBank> = {
  "adults-only": { center: "cbd", kind: "store", vertical: "retail", secondary: [], cores: P(["Velvet Door", "Midnight Mart", "Crimson Shelf", "Noir Nights", "After Hours", "Private Reserve"]), premiumCores: P(["Maison Noir", "Velvet Reserve"]), prefixes: P(["The", "Casa", "Club"]), suffixes: P(["KE", "Nairobi", "Express", "& Co"]), blurbs: P(["Discreet {Sub} in {Area} — verified 18+, private packaging.", "Late-night {Sub} with fast boda delivery across {Area}.", "{Area}'s trusted {Sub} counter, open till late."]), tags: P(["discreet", "18+", "late-night"]), etaMin: ["25-40 min", "20-35 min"], minOrderKes: [500, 1500] },
  "airport-transfers": { center: "jkia", kind: "service", vertical: "transport", secondary: ["car-rental", "meet-greet", "executive-travel"], cores: P(["Runway Rides", "Skyline Transfers", "Ndege Express", "Terminal Taxis", "GateLink", "Airstrip Cars"]), premiumCores: P(["Executive Runway", "First Class Transfers"]), prefixes: P(["", "Swift"]), suffixes: P(["KE", "Shuttles", "Ltd"]), blurbs: P(["Flight-tracked {Sub} on the JKIA corridor.", "{Sub} with meet & greet boards and free waiting time.", "Corporate {Sub} — receipts instant, cars spotless."]), tags: P(["flight-tracked", "meet-greet", "corporate"]), etaMin: ["15-25 min", "10-20 min"], minOrderKes: [1200, 3500] },
  "alcohol-beverages": { center: "westlands", kind: "store", vertical: "food", secondary: ["party-supplies", "mixers"], cores: P(["Baraka Bottles", "Rift Valley Cellar", "Tipsy Trolley", "Mabati Bar", "Grapevine KE", "Last Call Liquor"]), premiumCores: P(["Cellar Reserve", "Single Malt House"]), prefixes: P(["The", "Old"]), suffixes: P(["Wines & Spirits", "Liquor Store", "KE"]), blurbs: P(["Chilled {Sub} delivered in {Area} in under an hour.", "{Sub} for the weekend — party packs and crates.", "Rare finds and everyday {Sub} at honest prices."]), tags: P(["chilled", "party-packs", "18+"]), etaMin: ["30-50 min", "20-40 min"], minOrderKes: [800, 2500] },
  "fashion-apparel": { center: "cbd", kind: "store", vertical: "retail", secondary: ["tailoring", "styling"], cores: P(["Mama Njoroge Fits", "Thrift254", "Kitenge Lab", "Nairobi Attire", "Soko Styles", "Zawadi Wear"]), premiumCores: P(["Atelier Kilimani", "House of Ankara"]), prefixes: P(["The", "New"]), suffixes: P(["Boutique", "Fashion House", "KE", "Thrift"]), blurbs: P(["{Sub} drops every Friday — {Area} sizes up to 3XL.", "Mitumba-gem {Sub}, steamed and ready.", "Made-in-Kenya {Sub} from local fundis."]), tags: P(["new-drops", "mitumba", "local-made"]), etaMin: ["45-90 min", "30-60 min"], minOrderKes: [1000, 5000] },
  "beauty": { center: "kilimani", kind: "store", vertical: "beauty", secondary: ["salon-booking", "bridal"], cores: P(["Glow254", "Shea & Co", "Rembo Shades", "Urembo Hub", "Pedi Palace", "Curl Culture"]), premiumCores: P(["Maison de Glow", "The Ivory Comb"]), prefixes: P(["The", "House of"]), suffixes: P(["Beauty", "Cosmetics", "KE"]), blurbs: P(["100% genuine {Sub} — receipts from authorised distributors.", "{Sub} for melanin-rich skin, tested in {Area}.", "Shade-match help on chat before you buy."]), tags: P(["genuine", "shade-match", "cruelty-free"]), etaMin: ["30-60 min", "20-45 min"], minOrderKes: [600, 3000] },
  "vehicle-rentals": { center: "westlands", kind: "service", vertical: "transport", secondary: ["airport-transfer", "safari", "chauffeur"], cores: P(["Barabara Rentals", "Safari Wheels", "Mabasi Motors", "Twende Cars", "Rift Hire", "City Hop Cars"]), premiumCores: P(["Prestige Fleet", "Land Cruiser Legends"]), prefixes: P(["", "Royal"]), suffixes: P(["Car Hire", "Rentals", "KE"]), blurbs: P(["Self-drive {Sub} with full insurance and 24h rescue.", "{Sub} with driver — fuel, guide and park fees handled.", "Corporate {Sub} with monthly billing."]), tags: P(["insured", "with-driver", "self-drive"]), etaMin: ["1-3 hrs", "45-90 min"], minOrderKes: [3500, 12000] },
  "experiences": { center: "cbd", kind: "booking", vertical: "experiences", secondary: ["photography", "catering", "tickets"], cores: P(["Nairobi Nights Live", "Sofar254", "Stage254", "Vibe Republic", "Mizizi Events", "Jamhuri Shows"]), premiumCores: P(["Carnivore Grounds Live", "K1 Klub House Sessions"]), prefixes: P(["", "The"]), suffixes: P(["Live", "Events", "KE"]), blurbs: P(["Verified {Sub} tickets — no brokers, no fakes.", "{Sub} every weekend across {Area}.", "Early-bird {Sub} passes with M-Pesa checkout."]), tags: P(["verified-tickets", "weekend", "early-bird"]), etaMin: ["Instant", "Instant"], minOrderKes: [500, 2500] },
  "financial-services": { center: "cbd", kind: "service", vertical: "services", secondary: ["business-services"], cores: P(["PesaLink Point", "Sacco Desk 254", "Forex Corner", "Mali Advisors", "Chama Hub", "Biashara Bureau"]), premiumCores: P(["Private Wealth KE", "Sterling Advisory"]), prefixes: P(["", "Trusted"]), suffixes: P(["Services", "Bureau", "KE"]), blurbs: P(["Licensed {Sub} with same-day processing.", "{Sub} in {Area} — walk in, walk out sorted.", "M-Pesa and bank rails supported."]), tags: P(["licensed", "same-day", "m-pesa"]), etaMin: ["30-60 min", "15-30 min"], minOrderKes: [0, 0] },
  "flowers-gifts": { center: "kilimani", kind: "store", vertical: "retail", secondary: ["cakes", "cards", "delivery"], cores: P(["Maua254", "Petal & Post", "Zawadi Box", "Blossom Boda", "Roses Rush", "Gift Garage"]), premiumCores: P(["The Flower Studio", "Orchid & Oak"]), prefixes: P(["", "The"]), suffixes: P(["Florist", "Gifts", "KE"]), blurbs: P(["Farm-fresh {Sub} arranged to order in {Area}.", "Same-day {Sub} with a handwritten card.", "Subscriptions for weekly {Sub}."]), tags: P(["farm-fresh", "same-day", "gift-wrap"]), etaMin: ["45-90 min", "30-60 min"], minOrderKes: [800, 3000] },
  "restaurants-food": { center: "kilimani", kind: "restaurant", vertical: "food", secondary: ["catering", "cakes", "juice-bar"], cores: P(["Mama Oliech Kitchen", "Kilimani Food Lab", "Nyama Villa", "Pilau Palace", "Chapati House", "Smocha Spot", "Ugali Yard", "Biriani Base"]), premiumCores: P(["Tamarind Kilimani", "The Carnivore Counter"]), prefixes: P(["", "New", "Big Square"]), suffixes: P(["Kitchen", "Eatery", "Grill", "KE"]), blurbs: P(["{Sub} that {Area} queues for — served hot, packed tight.", "Family {Sub} portions, M-Pesa prices.", "Late-night {Sub} till 11pm."]), tags: P(["hot-fresh", "family-size", "late-night"]), etaMin: ["20-40 min", "15-30 min"], minOrderKes: [300, 1000] },
  "groceries-essentials": { center: "kilimani", kind: "store", vertical: "grocery", secondary: ["butchery", "fresh-produce"], cores: P(["Mboga Fresh", "Soko Direct", "Jikoni Basket", "Daily Greens", "Chakula Mart", "Freshi KE"]), premiumCores: P(["Organic Kilimani", "The Butcher Block"]), prefixes: P(["", "Fresh"]), suffixes: P(["Groceries", "Mart", "Fresh", "KE"]), blurbs: P(["Morning-market {Sub}, picked today.", "{Sub} weighed honestly, bagged free.", "Weekly staples box for {Area} flats."]), tags: P(["farm-direct", "weighed-fair", "staples-box"]), etaMin: ["30-60 min", "20-40 min"], minOrderKes: [400, 1500] },
  "laundry-cleaning": { center: "kilimani", kind: "service", vertical: "services", secondary: ["dry-cleaning", "home-cleaning"], cores: P(["Fua Rangi", "Sparkle Press", "Nguo Safi", "Wash & Fold 254", "Iron Lady", "Deep Clean Crew"]), premiumCores: P(["The Press Club", "White Glove KE"]), prefixes: P(["", "Express"]), suffixes: P(["Laundry", "Cleaners", "KE"]), blurbs: P(["48-hour {Sub} with free pickup in {Area}.", "Stain-treated {Sub}, pressed crisp.", "Move-in/move-out {Sub} squads."]), tags: P(["free-pickup", "48hr", "stain-care"]), etaMin: ["2-4 hrs", "1-2 hrs"], minOrderKes: [400, 1200] },
  "marketplace": { center: "eastleigh", kind: "store", vertical: "retail", secondary: ["delivery", "assembly"], cores: P(["Dubois Road Deals", "Luthuli Finds", "Soko Mjinga", "Kamukunji Corner", "River Road Retail", "Gikomba Gold"]), premiumCores: P(["Furniture Palace", "The Decor Loft"]), prefixes: P(["", "New"]), suffixes: P(["Stores", "Mall", "KE", "Hub"]), blurbs: P(["Wholesale-priced {Sub} in {Area}.", "{Sub} with delivery and assembly.", "Bargain {Sub}, tested before dispatch."]), tags: P(["wholesale", "assembly", "tested"]), etaMin: ["60-120 min", "30-60 min"], minOrderKes: [1000, 5000] },
  "pharmacy": { center: "kilimani", kind: "store", vertical: "pharmacy", secondary: ["teleconsult", "baby-care"], cores: P(["Dawa Express", "Afya Chemist", "MediRush", "Jumuiya Pharma", "CarePlus Duka", "Halisi Health"]), premiumCores: P(["The Village Chemist", "Pharmaplus Care"]), prefixes: P(["", "Trusted"]), suffixes: P(["Pharmacy", "Chemist", "KE"]), blurbs: P(["PPB-licensed {Sub} with pharmacist on chat.", "Chronic-refill {Sub} reminders free.", "Sealed, genuine {Sub} only."]), tags: P(["licensed", "pharmacist-chat", "genuine"]), etaMin: ["20-40 min", "15-30 min"], minOrderKes: [200, 800] },
  "health": { center: "kilimani", kind: "booking", vertical: "wellness", secondary: ["labs", "telemedicine"], cores: P(["Afya Pap", "Malaika Clinics", "Tiba At Home", "Mind Spa KE", "Uzima Labs", "Coach254"]), premiumCores: P(["Aga Khan Outreach", "The Wellness Suite"]), prefixes: P(["", "Family"]), suffixes: P(["Clinic", "Care", "KE"]), blurbs: P(["Booked {Sub} with licensed practitioners.", "Home-visit {Sub} across {Area}.", "Results and scripts on WhatsApp + app."]), tags: P(["licensed", "home-visit", "bookable"]), etaMin: ["Same day", "1-2 hrs"], minOrderKes: [800, 3000] },
  "tech-electronics": { center: "cbd", kind: "store", vertical: "retail", secondary: ["repairs", "accessories"], cores: P(["Luthuli Tech", "Simu Soko", "Gadget Base", "Charge Up KE", "Screen Fix Fundis", "Byte Mart"]), premiumCores: P(["iStore Kilimani", "The Audio Room"]), prefixes: P(["", "New"]), suffixes: P(["Tech", "Gadgets", "KE", "Hub"]), blurbs: P(["Genuine {Sub} with warranty cards.", "{Sub} tested in front of you on delivery.", "Lipa-mdogo-mdogo {Sub} plans."]), tags: P(["warranty", "tested-live", "lipa-mdogo"]), etaMin: ["45-90 min", "30-60 min"], minOrderKes: [1500, 8000] },
  "travel-tours": { center: "cbd", kind: "booking", vertical: "travel", secondary: ["car-rental", "airport-transfer", "photography"], cores: P(["Twende Safari", "Mara Express", "Savanna Trails", "Rift Adventures", "Zebra Routes", "Flamingo Tours"]), premiumCores: P(["Lux Mara Camps", "Private Safari Co"]), prefixes: P(["", "Royal"]), suffixes: P(["Safaris", "Tours", "Adventures", "KE"]), blurbs: P(["KWS-licensed {Sub} with pop-top vans.", "{Sub} with park fees clearly itemised.", "Multi-day {Sub} with hotel handoffs."]), tags: P(["licensed", "pop-top", "park-fees-clear"]), etaMin: ["Same day", "2-4 hrs"], minOrderKes: [5000, 25000] },
  "vehicle-services": { center: "westlands", kind: "service", vertical: "services", secondary: ["car-wash", "rescue"], cores: P(["Nai Wash", "Pressure Point", "Mud Off KE", "Sparkle Rides", "Puncture Pros", "Battery Boys"]), premiumCores: P(["Detailing Studio", "Ceramic Coat KE"]), prefixes: P(["", "Express"]), suffixes: P(["Car Wash", "Auto Care", "KE"]), blurbs: P(["Doorstep {Sub} with own water and power.", "{Sub} in {Area} while you work.", "Rescue {Sub} day and night."]), tags: P(["doorstep", "own-water", "24-7"]), etaMin: ["45-90 min", "30-60 min"], minOrderKes: [500, 2000] },
  "wellness": { center: "kilimani", kind: "booking", vertical: "wellness", secondary: ["massage", "gym-day-pass"], cores: P(["Amani Spa", "Tulia Massage", "Pumzika House", "Zen Garden KE", "Sweat Society", "Glow & Go"]), premiumCores: P(["Serena Spa Counter", "The Hammam Room"]), prefixes: P(["", "The"]), suffixes: P(["Spa", "Wellness", "KE"]), blurbs: P(["Bookable {Sub} with vetted therapists.", "Couples {Sub} rooms in {Area}.", "Day-pass {Sub} with towel + chai."]), tags: P(["vetted", "couples", "bookable"]), etaMin: ["Same day", "1-2 hrs"], minOrderKes: [1500, 6000] },
  "concierge-services": { center: "karen", kind: "service", vertical: "services", secondary: ["reservations", "gift-sourcing", "cleaning"], cores: P(["Nia Concierge", "Karibu Desk", "Sorted KE", "Errandly", "Front Row KE", "White Rabbit"]), premiumCores: P(["Private Office KE", "The Members Desk"]), prefixes: P(["", "The"]), suffixes: P(["Concierge", "Desk", "KE"]), blurbs: P(["One chat for all your {Sub} in {Area}.", "{Sub} with receipts for everything.", "Retainer {Sub} for busy households."]), tags: P(["one-chat", "receipted", "retainer"]), etaMin: ["1-2 hrs", "30-60 min"], minOrderKes: [1000, 5000] },
  "logistics-shipping": { center: "jkia", kind: "service", vertical: "services", secondary: ["warehousing", "last-mile"], cores: P(["Mizigo Movers", "Transmara Freight", "SGR Link Cargo", "Parcel Pod", "Container KE", "Upcountry Haul"]), premiumCores: P(["DHL Counter KE", "Cold Chain Co"]), prefixes: P(["", "Swift"]), suffixes: P(["Logistics", "Cargo", "Movers", "KE"]), blurbs: P(["Tracked {Sub} with POD photos.", "{Sub} with warehousing at Syokimau.", "Upcountry {Sub} nightly departures."]), tags: P(["tracked", "pod-photo", "upcountry"]), etaMin: ["2-6 hrs", "1-3 hrs"], minOrderKes: [800, 4000] },
};
