export { NexGText } from './NexGText';
export { NexGButton } from './NexGButton';
export { NexGChip } from './NexGChip';
export { NexGPrice } from './NexGPrice';
export { NexGRating } from './NexGRating';
export { NexGSectionHeader } from './NexGSectionHeader';
export { NexGEmptyState, NexGErrorState } from './NexGStates';
// NOTE: admin-web keeps the lean skeleton export (its NexGSkeleton has no
// card/row variants) — when copying shared index.ts, keep this line trimmed.
export { NexGSkeleton, NexGSkeletonRow, NexGSectionSkeleton } from './NexGSkeleton';
export { NexGSkeletonView, AutoSkeletonIgnoreView } from './NexGSkeletonView';
export { NexGQuantitySelector } from './NexGQuantitySelector';
export { NexGSearchBar } from './NexGSearchBar';
export { NexGBadge } from './NexGBadge';
export { NexGBottomSheet } from './NexGBottomSheet';
export { NexGConfirm } from './NexGConfirm';
export { NexGLogo, NEXG_ACCENT, NEXG_INK_LIGHT, NEXG_INK_DARK, NEXG_SPLASH_BG_LIGHT, NEXG_SPLASH_BG_DARK } from './NexGLogo';
export { NexGSplash } from './NexGSplash';
export { NexGPillTabBar } from './NexGPillTabBar';
export { NexGOTPInput, NexGOTPInputWithSeparator } from './NexGOTPInput';
export type { NexGOTPInputProps, NexGOTPInputRef } from './NexGOTPInput';
export { NexGSwitch } from './NexGSwitch';
export type { NexGSwitchProps } from './NexGSwitch';
export { NexGCheckbox } from './NexGCheckbox';
export type { NexGCheckboxProps } from './NexGCheckbox';
export { NexGRadioButton, NexGRadioGroup } from './NexGRadio';
export type { NexGRadioButtonProps, NexGRadioGroupProps, NexGRadioOption } from './NexGRadio';
export { NexGCard, NexGCardHeader, NexGCardTitle, NexGCardDescription, NexGCardContent, NexGCardFooter } from './NexGCard';
export type { NexGCardProps, NexGCardHeaderProps, NexGCardTitleProps, NexGCardDescriptionProps, NexGCardContentProps, NexGCardFooterProps } from './NexGCard';
export { NexGToastProvider, NexGToast, useNexGToast } from './NexGToast';
export type { NexGToastVariant, NexGToastData, NexGToastProps, NexGToastProviderProps } from './NexGToast';
export { NexGCarousel, NexGCarouselContent, NexGCarouselItem, NexGCarouselIndicators, NexGCarouselArrow } from './NexGCarousel';
export type { NexGCarouselProps, NexGCarouselContentProps, NexGCarouselItemProps, NexGCarouselIndicatorsProps, NexGCarouselArrowProps, NexGCarouselRef } from './NexGCarousel';
export { NexGTable } from './NexGTable';
export type { NexGTableColumn, NexGTableProps } from './NexGTable';
export { NexGInput, NexGGroupedInput, NexGGroupedInputItem } from './NexGInput';
export type { NexGInputProps, NexGGroupedInputProps, NexGGroupedInputItemProps } from './NexGInput';
export { NexGPicker } from './NexGPicker';
export type { NexGPickerOption, NexGPickerSection, NexGPickerProps } from './NexGPicker';
export { NexGMediaPicker } from './NexGMediaPicker';
export type { NexGMediaType, NexGMediaQuality, NexGMediaAsset, NexGMediaPickerProps, NexGMediaPickerSize, NexGMediaPickerVariant } from './NexGMediaPicker';
export { NexGCamera, NexGCameraPreview } from './NexGCamera';
export type { NexGCaptureSuccess, NexGCameraProps, NexGCameraRef, NexGCameraPreviewProps } from './NexGCamera';
export { NexGDatePicker } from './NexGDatePicker';
export type { NexGDateRange, NexGDatePickerProps } from './NexGDatePicker';
export { NexGExperienceChips } from './NexGExperienceChips';
export { NexGAuthGate } from './NexGAuthGate';
export { NexGGuestBanner } from './NexGGuestBanner';
export { NexGCapabilityCard } from './NexGCapabilityCard';
export type { NexGCapabilityCardProps } from './NexGCapabilityCard';
export { NexGWelcomeHero } from './NexGWelcomeHero';
export { NexGItemSheet } from './NexGItemSheet';
export type { NexGItemSheetProps, NexGItemSheetSelection } from './NexGItemSheet';
